# Generated by Django 3.0.8 on 2020-07-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=140)),
                ('starting_bid', models.IntegerField()),
                ('URL_image', models.URLField(max_length=64)),
                ('category', models.CharField(choices=[('TOYS', 'Toys'), ('FASHION', 'Fashion'), ('ELECTRONICS', 'Electronics'), ('SPORTS', 'Sports'), ('HOME', 'Home'), ('OTHER', 'Other')], default='OTHER', max_length=11)),
            ],
        ),
    ]
