# Generated by Django 3.0.8 on 2020-07-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200707_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='Product',
            field=models.ManyToManyField(blank=True, related_name='Bids', to='auctions.Listing'),
        ),
    ]
