# Generated by Django 3.0.8 on 2020-07-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200708_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Product',
            field=models.ManyToManyField(blank=True, related_name='User', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='bid',
            field=models.IntegerField(blank=True, default=100),
            preserve_default=False,
        ),
    ]
