# Generated by Django 3.0.8 on 2020-07-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200708_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bid',
        ),
        migrations.AddField(
            model_name='user',
            name='bid',
            field=models.ManyToManyField(blank=True, related_name='Bid', to='auctions.Bids'),
        ),
    ]
