# Generated by Django 3.0.8 on 2020-07-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200708_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bid',
            field=models.ManyToManyField(blank=True, related_name='User', to='auctions.Bids'),
        ),
    ]
