# Generated by Django 3.0.8 on 2020-07-08 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200708_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='Listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Bids', to='auctions.Listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Bids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
