# Generated by Django 3.0.8 on 2020-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.IntegerField(blank=True, default=100),
            preserve_default=False,
        ),
    ]
