# Generated by Django 3.0.8 on 2020-07-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_listing_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'get_latest_by': 'bid'},
        ),
    ]
